project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - pages/
website:
  title: "BitStat2 Live"
format:
  live-html:
    theme: cosmo
    toc: true
    include-in-header: _header.html
engine: knitr
resources:
  - assets
